version: '3.8'
services:
  backend:
    image: sajedbenhamza/to-listvueapp-backend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
  frontend:
    image: sajedbenhamza/to-listvueapp-frontend:latest
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
